### ISSUE TITLE
MCU handshake timed out!

### ISSUE THREAD

**Issue by TurBoss** [tmarinescu/PicoOS#21]
Hello,
nice project

I tried compiling on linux and when i burn it to the board usind debug port or uf2
i get this error on the serial port :/

```
Searching for MCU handshake...........................
MCU handshake timed out!
picoOS>>
```
is this normal?
thx!

**Comment by tmarinescu** [comment]
Yes, this project at the moment is being used together with other Pico boards connected together. You can just remove the task that handles that in the demo part.

aka;
`pOS_scheduler::create_task(&wait_for_other_board, 
		0, 
		pOS_task_quanta::heavy, 
		pOS_task_priority::normal, 
		&id);
	pOS_scheduler::enable_task(id);`

**Comment by tmarinescu** [comment]
Also remove
`uint32_t* mcu_ptr = (uint32_t*)pOS_memory::wait_for_memory_id(MEM_ID_MCU_STATUS);`
and
`if (*mcu_ptr == 0)
{
/* MCU handshake didn't succeed/timeout */
return 0;
}`
from the uart_input_task()

**Comment by TurBoss** [comment]
Thank you so much!
